[workspace]
members = ["crates/*"]
resolver = "3"

[patch.crates-io]
egui_ltreeview = { git = "https://github.com/landaire-contrib/egui_ltreeview", branch = "large_node_perf_fix" }
# egui_ltreeview = { path = "/Users/lander/src/egui_ltreeview" }
vfs = { git = "https://github.com/landaire/rust-vfs.git", branch = "fix/wasm" }
#vfs = { path = "../rust-vfs" }
