[package]
name = "enfusion_pak"
version = "0.1.0"
edition = "2024"
readme = "README.md"
repository = "https://github.com/landaire/enfusion_tools"
authors = ["Lander Brandt"]
documentation = "https://docs.rs/enfusion_pak"
homepage = "https://landaire.github.io/enfusion_tools"
license = "MIT OR Apache-2.0"
keywords = ["arma", "reforger", "enfusion"]

[[bin]]
name = "enfusion_pak"
path = "src/main.rs"
required-features = ["bin"]

[dependencies]
clap = { version = "4.5.37", features = ["derive"], optional = true }
jiff = "0.2.10"
kinded = "0.3.0"
memmap2 = { version = "0.9.5", optional = true }
thiserror = "2.0.12"
variantly = "0.4.0"
winnow = "0.7.7"
color-eyre = { version = "0.6", optional = true }
humansize = { version = "2.0.0", optional = true }
vfs = "0.12.1"
flate2 = "1.1.1"
wasm-bindgen-futures = "0.4.50"
log = "0.4.27"
async-trait = "0.1.88"
async-std = "1.13.1"

[features]
default = []
arc = []
async_vfs = ["vfs/async-vfs"]
bin = ["dep:clap", "dep:color-eyre", "dep:memmap2", "dep:humansize"]
